---
title: "Figure 3"
output: rmarkdown::github_document
---

```{r message=FALSE}
library(reticulate)
library(gtools)
library(tidyverse)
library(ggplot2)
library(DESeq2)
library(glue)
library(magrittr)
library(VennDiagram)
library(ComplexHeatmap)
library(circlize)
library(ggpubr)
library(ggrepel)

use_python("/projects/home/nealpsmith/.conda/envs/old_peg_github/bin/python")
```


```{python message=FALSE}
import getpass
import pegasus as pg
import scanpy as sc
import os
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import anndata
import math
import seaborn as sns
import matplotlib.colors as clr
from pylab import cm
import matplotlib as mpl
from matplotlib.lines import Line2D
from mpl_toolkits.axes_grid1 import make_axes_locatable
from scipy.sparse import csr_matrix
from collections import Counter
import wot
import pickle

from cellrank.external.kernels import WOTKernel
from cellrank.tl.kernels import ConnectivityKernel
from cellrank.tl.estimators import GPCCA
from mpl_toolkits.axes_grid1 import make_axes_locatable, Size

mpl.rcParams['axes.spines.right'] = False
mpl.rcParams['axes.spines.top'] = False
# mpl.rcParams['pdf.fonttype'] = 42

# Set a colormap
gene_colormap = clr.LinearSegmentedColormap.from_list('gene_cmap', ["#e0e0e1", '#4576b8', '#02024a'], N=200)

# Set a switcher up so the script will run on any computer
def file_path(user = getpass.getuser()):
    switcher = {
            "nealp": "C:/Users/nealp/Documents/Dropbox (Partners HealthCare)/Chloe&Mazen/Collaborator_projects/Kupper_TRM/neal_analysis",
            "neal": "/home/neal/Documents/Dropbox (Partners HealthCare)/Chloe&Mazen/Collaborator_projects/Kupper_TRM/neal_analysis",
            "nealpsmith": "/projects/home/nealpsmith/projects/kupper"

    }
    if switcher.get(user):
        return(switcher.get(user))
    else :
        print("Add your local filepath to the switcher! run getpass.getuser() to get your ID")

```


```{python fig_3A}

cmap = cm.get_cmap('YlGnBu', 140)    # PiYG
hex_list = []
for i in range(cmap.N):
    rgba = cmap(i)
    # rgb2hex accepts rgb or rgba
    hex_list.append(mpl.colors.rgb2hex(rgba))

colors = [c for n, c in enumerate(hex_list) if n%10 == 0]
colors = colors [1:13] # First one is too dim
days = ["0", "3", "4", "5", "6", "7", "10", "14", "21", "32", "60", "90"]

day_col_dict = dict(zip(days, colors))
# Also make as a colormap
kurd_day_cmap = clr.LinearSegmentedColormap.from_list('day_cmap', colors, N=len(colors))

cmap = cm.get_cmap('YlOrRd', 110)    # PiYG
hex_list = []
for i in range(cmap.N):
    rgba = cmap(i)
    # rgb2hex accepts rgb or rgba
    hex_list.append(mpl.colors.rgb2hex(rgba))

colors = [c for n, c in enumerate(hex_list) if n%10 == 0]
colors = colors [1:11] # First one is too dim
days = ["0", "2", "5", "10", "15", "20", "25", "30", "45", "60"]

day_col_dict = dict(zip(days, colors))
kupper_day_cmap = clr.LinearSegmentedColormap.from_list('day_cmap', colors, N=len(colors))

# Make a gene colormap too
gene_colormap = clr.LinearSegmentedColormap.from_list('gene_cmap', ["#d3d3d3", '#482cc7'], N=200)

gut1_data = pg.read_input(os.path.join(file_path(), "kurd_paper", "data", "gut1_data_subcluster.h5ad"))
skin1_data = pg.read_input(os.path.join(file_path(), "all_data_analysis", "data", "integrated", "skin1_subcluster.h5ad"))
skin1_data.obs["day"] = [int(d) for d in skin1_data.obs["day"]]
data_dict = {"skin" : skin1_data, "siIEL" : gut1_data}
day_cmaps = {"skin": kupper_day_cmap, "siIEL" : kurd_day_cmap}

### UMAP BY DAY ###
fig, ax = plt.subplots(nrows=1, ncols=2, figsize = (10, 4))
ax = ax.ravel()
for num, tissue in enumerate(data_dict.keys()) :
    dat = data_dict[tissue]
    plot_df = dat.obs[["day"]]
    int_dict = {k: v for k, v in zip(sorted(set(plot_df["day"]), key=int), range(len(set(plot_df["day"]))))}
    plot_df["day_int"] = [int_dict[d] for d in plot_df["day"]]
    plot_df["x"] = dat.obsm[f"X_umap"][:, 0]
    plot_df["y"] = dat.obsm[f"X_umap"][:, 1]
    # Get the colormap
    day_cmap = day_cmaps[tissue]
    ax[num].hexbin(plot_df["x"], plot_df["y"], C=plot_df["day_int"], cmap=day_cmap, gridsize=150, edgecolors="none")
    ax[num].get_xaxis().set_ticks([])
    ax[num].get_yaxis().set_ticks([])
    ax[num].set_xlabel("UMAP1")
    ax[num].set_ylabel("UMAP2")
    ax[num].set_title(tissue)

    divider = make_axes_locatable(ax[num])
    pad = 0.07
    pad_size = Size.Fraction(pad, Size.AxesY(ax[num]))

    xsize = Size.Fraction(0.05, Size.AxesX(ax[num]))
    ysize = Size.Fraction(0.5 - pad / 2., Size.AxesY(ax[num]))

    divider.set_horizontal([Size.AxesX(ax[num]), pad_size, xsize])
    divider.set_vertical([ysize, pad_size, ysize])

    ax[num].set_axes_locator(divider.new_locator(0, 0, ny1=-1))

    cax = mpl.axes.Axes(ax[num].get_figure(),
                        ax[num].get_position(original=True))
    locator = divider.new_locator(nx=2, ny=0)
    cax.set_axes_locator(locator)

    fig.add_axes(cax)
    plot_df["day"] = plot_df["day"].astype("object")
    bounds = np.array(sorted(set(plot_df["day"])))
    norm = mpl.colors.BoundaryNorm(bounds, day_cmap.N)

    cb = mpl.colorbar.ColorbarBase(cax, cmap=day_cmap, norm=norm,
                                   spacing='uniform', ticks=bounds, boundaries=bounds, format='%1i')
    cax.set_title("Day")

fig

```


```{r 3B_lin_modeling, message = FALSE, warning = FALSE, fig.height = 6, fig.width = 6}

padj_cutoff = 0.1
perc_cells_cutoff = 5
slope_cutoff = 0.2

# Load in the counts and metadata
count_data_kupper <- read.csv("/projects/home/nealpsmith/projects/kupper/all_data_analysis/data/integrated/skin1_subcluster_pseudobulk_on_time_counts.csv", row.names = 1)
meta_data_kupper <- read.csv("/projects/home/nealpsmith/projects/kupper/all_data_analysis/data/integrated/skin1_subcluster_pseudobulk_on_time_meta.csv",
                  row.names = 1)

meta_temp <- meta_data_kupper[meta_data_kupper$n_cells > 100,]

# Remove the extra D30 sample, seems unfair to only have 2 samples for one timepoint
meta_temp <- meta_temp[rownames(meta_temp) != "samp_19_D30_Skin_30",]
# Need to adjust the int to the lowest point
meta_temp$day_int <- meta_temp$day_int - 2

count_temp <- count_data_kupper[,rownames(meta_temp)]

# Make sure the genes are detected in enough samples
n_samp <- rowSums(count_temp != 0)
count_temp <- count_temp[n_samp > round(nrow(meta_temp) / 2),]
count_temp <- count_temp[!grepl("Gm[0-9]|Rpl|Rps|mt-|-ps", rownames(count_temp)),]

# Okay now we can run DESeq
dds_kupper <- DESeqDataSetFromMatrix(countData = count_temp,
                            colData = meta_temp,
                            design = ~day_int)
dds_kupper <- DESeq(dds_kupper)
skin_res <- as.data.frame(results(dds_kupper))
skin_res <- skin_res[!is.na(skin_res$padj),]
skin_res$gene <- rownames(skin_res)
# Read in the single cell gene info
gene_info <- read.csv("/projects/home/nealpsmith/projects/kupper/all_data_analysis/data/integrated/skin1_subcluster_gene_info.csv") %>%
  rename(feature = "gene")

skin_res %<>%
  left_join(gene_info, by = "gene")

skin_de <- skin_res[skin_res$padj < padj_cutoff & abs(skin_res$log2FoldChange) > slope_cutoff
                  & skin_res$percent_cells > perc_cells_cutoff,] %>%
    arrange(padj)

#### Now the gut modeling ####

# Load in the counts and metadata
count_data_kurd <- read.csv("/projects/home/nealpsmith/projects/kupper/kurd_paper/data/gut1_data_subcluster_pseudobulk_on_time_counts.csv",
                     row.names = 1)
meta_data_kurd <- read.csv("/projects/home/nealpsmith/projects/kupper/kurd_paper/data/gut1_data_subcluster_pseudobulk_on_time_meta.csv",
                  row.names = 1)

meta_temp <- meta_data_kurd[meta_data_kurd$n_cells > 100,]
count_temp <- count_data_kurd[,rownames(meta_temp)]

# Make sure the genes are detected in enough samples
n_samp <- rowSums(count_temp != 0)
count_temp <- count_temp[n_samp > round(nrow(meta_temp) / 2),]
count_temp <- count_temp[!grepl("Gm[0-9]|Rpl|Rps|mt-|-ps", rownames(count_temp)),]

# Okay now we can run DESeq
dds_kurd <- DESeqDataSetFromMatrix(countData = count_temp,
                            colData = meta_temp,
                            design = ~day_int)
dds_kurd <- DESeq(dds_kurd)
gut_res <- as.data.frame(results(dds_kurd))
gut_res <- gut_res[!is.na(gut_res$padj),]
gut_res$gene <- rownames(gut_res)
# Read in the single cell gene info
gene_info <- read.csv("/projects/home/nealpsmith/projects/kupper/kurd_paper/data/gut1_data_subcluster_gene_info.csv") %>%
rename(feature = "gene")

gut_res %<>%
  left_join(gene_info, by = "gene")

gut_de <- gut_res[gut_res$padj < padj_cutoff & abs(gut_res$log2FoldChange) > slope_cutoff
                    & gut_res$percent_cells > perc_cells_cutoff,] %>%
  arrange(padj)

skin_mem <- skin_de[skin_de$log2FoldChange > 0,]
gut_mem <- gut_de[gut_de$log2FoldChange > 0,]

skin_genes <- skin_mem$gene
gut_genes <- gut_mem$gene
kupper_trm <- intersect(skin_genes, gut_genes)

venn_tissue_mem <- draw.pairwise.venn(length(skin_genes), length(gut_genes), length(kupper_trm),
                   category = c("Skin", "siIEL"), fill = c("red", "blue"),
                   lwd = rep(0, 2), cex = rep(unit(1, "cm"), 3),
                   cat.pos = c(180, 180), cat.cex = rep(unit(1, "cm"), 2))
venn_tissue_mem

```

```{r fig_3C, message = FALSE, warning = FALSE, fig.width = 5, fig.height = 10}

vsd_kupper <- vst(dds_kupper, blind=TRUE)
norm_res_kupper <- assay(vsd_kupper)

vsd_kurd <- vst(dds_kurd, blind = TRUE)
norm_res_kurd <- assay(vsd_kurd)

skin_only <- skin_mem$gene[!skin_mem$gene %in% kupper_trm]
skin_only <- skin_only[skin_only %in% gut_res$gene]
diff <- lapply(skin_only, function(x) skin_de$log2FoldChange[skin_de$gene == x] - gut_res$log2FoldChange[gut_res$gene == x])
skin_only_top_n <- data.frame(gene = skin_only, diff = unlist(diff)) %>%
  arrange(desc(diff)) %>%
  top_n(100) %>%
  .$gene
print(skin_only_top_n)

# Now for the gut
gut_only <- gut_mem$gene[!gut_mem$gene %in% kupper_trm]
gut_only <- gut_only[gut_only %in% skin_res$gene]
diff <- lapply(gut_only, function(x) gut_de$log2FoldChange[gut_de$gene == x] - skin_res$log2FoldChange[skin_res$gene == x])

gut_only_top_n <- data.frame(gene = gut_only, diff = unlist(diff)) %>%
  arrange(desc(diff)) %>%
  top_n(100) %>%
  .$gene
print(gut_only_top_n)
heatmap_genes <- c(skin_only_top_n, gut_only_top_n)
heatmap_genes <- heatmap_genes[heatmap_genes %in% rownames(norm_res_kurd) & heatmap_genes %in% rownames(norm_res_kupper)]

### Kupper heatmap ###
heatmap_mtx <- norm_res_kupper[heatmap_genes,]
heatmap_mtx <- t(scale(t(heatmap_mtx)))

colnames(heatmap_mtx) <- sapply(colnames(heatmap_mtx), function(x) strsplit(x, "_")[[1]][3])

# Re-order to be ordered by day
heatmap_mtx <-heatmap_mtx[,mixedsort(colnames(heatmap_mtx))]

# Day bar
days <- colnames(heatmap_mtx)

# Now make the day annotation
day_colors = list("Day" = c('D0'= '#fff2ac',
                            'D2'= '#ffe48c',
                            'D5'= '#fed16e',
                            'D10'= '#feb54f',
                            'D15'= '#fd9941',
                            'D20'= '#fd7435',
                            'D25'= '#f94728',
                            'D30'= '#e6211e',
                            'D45'= '#cc0a22',
                            'D60'= '#a80026'))

days <- factor(days, levels = c("D0", "D2", "D5", "D10", "D15", "D20", "D25", "D30", "D45", "D60"))
days <- droplevels(days)
day_bar = HeatmapAnnotation("Day" = days, col = day_colors,
                            show_legend = FALSE, show_annotation_name = FALSE)
# Heatmap colors
heatmap_col_fun = colorRamp2(c(min(heatmap_mtx), 0, max(heatmap_mtx)), c("purple", "black", "yellow"))

# Lets make the legends
day_fill <- sapply(levels(days), function(x) day_colors$Day[as.character(x)])
day_legend_skin <- Legend(labels = levels(days), legend_gp = gpar(fill = day_fill), title = "timepoint (skin)")

heatmap_lgd = Legend(col_fun = heatmap_col_fun, title = "z-score", legend_height = unit(4, "cm"), title_position = "topcenter")

lgd_list <- packLegend(heatmap_lgd, day_legend_skin, column_gap = unit(1,"cm"), direction = "vertical",
                     max_height = unit(14, "cm"))

# Get the split
split <- c(rep("Skin", length(skin_only_top_n)), rep("siIEL", length(gut_only_top_n)))
# split <- c(rep("both", length(kupper_trm)), rep("skin", length(skin_only)), rep("gut", length(gut_only)))

split <- factor(split, levels = c("Skin", "siIEL"))

kupper_hmap = Heatmap(heatmap_mtx, name = "z-score", col = heatmap_col_fun,
                 top_annotation = day_bar, show_column_names = FALSE, show_row_names = FALSE,
                 cluster_columns = FALSE, cluster_rows = FALSE,
                      show_heatmap_legend = FALSE, split = split,
                      column_title = "Skin")


### The gut heatmap ###
heatmap_mtx_kurd <- norm_res_kurd[heatmap_genes,]

# Get the average of the repeated timepoints
colname_to_tmpt <- lapply(colnames(heatmap_mtx_kurd), function(x) paste("D", tail(strsplit(x, "_")[[1]], n = 1), sep = ""))
tmpts <- unique(sapply(colnames(heatmap_mtx_kurd), function(x) tail(strsplit(x, "_")[[1]], n = 1)))

heatmap_mtx_kurd <- lapply(tmpts, function(tpt){
  cols = as.data.frame(heatmap_mtx_kurd[,grepl(glue("*_{tpt}$"), colnames(heatmap_mtx_kurd))])
  if(ncol(cols) > 1){
   mean = rowMeans(cols) %>%
    as.data.frame() %>%
    `colnames<-`(glue("D{tpt}")) %>%
     rownames_to_column("gene")
  return(mean)
  } else {
    cols <- cols %>%
      `colnames<-`(glue("D{tpt}")) %>%
     rownames_to_column("gene")
    return(cols)
  }
}) %>%
  purrr::reduce(left_join, by = "gene") %>%
  column_to_rownames("gene")

heatmap_mtx_kurd <- t(scale(t(heatmap_mtx_kurd)))

# Now the clustering
# clustering = hclust(dist(t(heatmap_mtx_kurd), method = "euclidean"), method = "ward.D2")
# col_hc <- as.dendrogram(clustering)

# Re-order to be ordered by day
heatmap_mtx_kurd <-heatmap_mtx_kurd[,mixedsort(colnames(heatmap_mtx_kurd))]

days <- colnames(heatmap_mtx_kurd)

day_colors = list("Day" = c('D0'= '#f5fbc2',
                            'D3'= '#e7f6b1',
                            'D4'= '#d1edb3',
                            'D5'= '#b1e1b6',
                            'D6'= '#88d0ba',
                            'D7'= '#63c3bf',
                            'D10'= '#40b5c4',
                            'D14'= '#2ba0c2',
                            'D21'= '#1e88bc',
                            'D32'= '#216aae',
                            'D60'= '#2350a1',
                            'D90'= '#253896'))

days <- factor(days, levels = c("D0", "D3", "D4", "D5", "D6", "D7", "D10", "D14", "D21", "D32", "D60", "D90"))
days <- droplevels(days)
day_bar = HeatmapAnnotation("Day" = days, col = day_colors,
                            show_legend = FALSE)

# Heatmap colors
heatmap_col_fun = colorRamp2(c(min(heatmap_mtx_kurd), 0, max(heatmap_mtx_kurd)), c("purple", "black", "yellow"))

# Lets make the legends
day_fill <- sapply(levels(days), function(x) day_colors$Day[as.character(x)])
day_legend_gut <- Legend(labels = levels(days), legend_gp = gpar(fill = day_fill), title = "timepoint (siIEL)")

heatmap_lgd = Legend(col_fun = heatmap_col_fun, title = "z-score", legend_height = unit(4, "cm"), title_position = "topcenter")


label_genes <- list( "Skin" = c("Ikzf2", "Ccr1", "Cd44", "Cd40lg", "Cd226", "Cd96", "Tbx21", "Il2rg"),
                    "siIEL" = c("Klrb1c", "Tox", "Cmip", "Zeb2", "Hspa1a", "Hspa1b", "Klf3", "Sesn1"))

gene_col_list <- c("Skin" = "red", "siIEL" = "blue")

gene_cols <- c()
for (set in names(label_genes)){
  gene_cols <- c(gene_cols, rep(gene_col_list[[set]], length(label_genes[[set]])))
}

all_genes <- unlist(label_genes, use.names = FALSE)
gene_legend <- Legend(labels = names(label_genes), legend_gp = gpar(fill = unique(gene_cols)),
                      title = "")

lgd_list <- packLegend(heatmap_lgd, day_legend_skin, day_legend_gut, gene_legend, column_gap = unit(1,"cm"), direction = "vertical",
                     max_height = unit(20, "cm"))


kurd_hmap = Heatmap(heatmap_mtx_kurd, name = "z-score", col = heatmap_col_fun,
               top_annotation = day_bar,
               show_column_names = FALSE,
               show_row_names = FALSE,
               cluster_columns = FALSE,
                    cluster_rows = FALSE,
                    show_heatmap_legend = FALSE,
                    split = split,
                    column_title = "siIEL") +
  rowAnnotation(link = anno_mark(at = match(all_genes, rownames(heatmap_mtx_kurd)),labels = all_genes,
                                 labels_gp = gpar(col = gene_cols, fontsize = 15, fontface = "bold")))

hmap_list <- kupper_hmap + kurd_hmap
draw(hmap_list, heatmap_legend_list = lgd_list)

```


```{r fig_3D, warning = FALSE, message = FALSE, fig.height = 10, fig.width = 12}

# Now need to log-norm
norm_res_kupper <- apply(count_data_kupper, 2, function(c){
  n_total <- sum(c)
  per_100k <- (c * 1000000) / n_total
  return(per_100k)
})
norm_res_kupper <- log1p(norm_res_kupper)
colnames(norm_res_kupper) <- sapply(colnames(norm_res_kupper), function(x) strsplit(x, "_")[[1]][3])

norm_res_kurd <- apply(count_data_kurd, 2, function(c){
  n_total <- sum(c)
  per_100k <- (c * 1000000) / n_total
  return(per_100k)
})
norm_res_kurd <- log1p(norm_res_kurd)

# Get the average of the repeated timepoints
colname_to_tmpt <- lapply(colnames(norm_res_kurd), function(x) paste("D", tail(strsplit(x, "_")[[1]], n = 1), sep = ""))
tmpts <- unique(sapply(colnames(norm_res_kurd), function(x) tail(strsplit(x, "_")[[1]], n = 1)))

norm_res_kurd <- lapply(tmpts, function(tpt){
  cols = as.data.frame(norm_res_kurd[,grepl(glue("*_{tpt}$"), colnames(norm_res_kurd))])
  if(ncol(cols) > 1){
   mean = rowMeans(cols) %>%
    as.data.frame() %>%
    `colnames<-`(glue("D{tpt}")) %>%
     rownames_to_column("gene")
  return(mean)
  } else {
    cols <- cols %>%
      `colnames<-`(glue("D{tpt}")) %>%
     rownames_to_column("gene")
    return(cols)
  }
}) %>%
  purrr::reduce(left_join, by = "gene") %>%
  column_to_rownames("gene")

# Now make the day annotation
day_colors = c('skin_D0'= '#fff2ac',
               'skin_D2'= '#ffe48c',
               'skin_D5'= '#fed16e',
               'skin_D10'= '#feb54f',
               'skin_D15'= '#fd9941',
               'skin_D20'= '#fd7435',
               'skin_D25'= '#f94728',
               'skin_D30'= '#e6211e',
               'skin_D45'= '#cc0a22',
               'skin_D60'= '#a80026',
               'siIEL_D0'= '#f5fbc2',
               'siIEL_D3'= '#e7f6b1',
               'siIEL_D4'= '#d1edb3',
               'siIEL_D5'= '#b1e1b6',
               'siIEL_D6'= '#88d0ba',
               'siIEL_D7'= '#63c3bf',
               'siIEL_D10'= '#40b5c4',
               'siIEL_D14'= '#2ba0c2',
               'siIEL_D21'= '#1e88bc',
               'siIEL_D32'= '#216aae',
               'siIEL_D60'= '#2350a1',
               'siIEL_D90'= '#253896')

genes_oi <- c("Ikzf2", "Ccr1", "Gzmc", "Atp8a2", "Gfi1", "Klf3")

gene_pairs <- data.frame("gene1" = rep("Itgae", length(genes_oi)),
                         "gene2" = genes_oi)
plot_list <- list()
for (i in 1:nrow(gene_pairs)){
  g1 <- gene_pairs[i, "gene1"]
  g2 <- gene_pairs[i, "gene2"]

  plot_info_kupper <- norm_res_kupper[c(g1, g2),] %>%
    t() %>%
    as.data.frame() %>%
    rownames_to_column(var = "tmpt") %>%
    mutate(tmpt_tissue = paste("skin", tmpt, sep = "_"))

  plot_info_kurd <- norm_res_kurd[c(g1, g2),] %>%
    t() %>%
    as.data.frame() %>%
    rownames_to_column(var = "tmpt") %>%
    mutate(tmpt_tissue = paste("siIEL", tmpt, sep = "_"))

  plot_df <- rbind(plot_info_kupper, plot_info_kurd)

  plot_df$tmpt_tissue <- factor(plot_df$tmpt_tissue, levels = names(day_colors))

  p <- ggplot(plot_df, aes_string(x = g1, y = g2, fill = "tmpt_tissue")) +
    geom_point(pch = 21, size = 5) +
    scale_fill_manual(values = day_colors) +
    xlab(glue("Log(CPM) : {g1}")) +
    ylab(glue("Log(CPM) : {g2}")) +
    # ggtitle(glue("{g2} vs. {g1}")) +
    theme_classic(base_size = 20)
  plot_df$tmpt_int <- sapply(plot_df$tmpt, function(x) as.numeric(sub("D", "", x)))
  plot_df$tissue <- sapply(as.character(plot_df$tmpt_tissue), function(x) strsplit(x, "_")[[1]][1])
  plot_df$tmpt_int <- factor(plot_df$tmpt_int)

  plot_list <- c(plot_list, list(p))
}

plots <- ggarrange(plotlist = plot_list, common.legend = TRUE)
plots

```


```{r fig_3E, warning = FALSE, message = FALSE}

### First the siIEL ###
gut1_aucell <- read.csv('/projects/home/nealpsmith/projects/kupper/pyscenic/res/gut1/gut1.auc_with_timepoint.csv', row.names = 1)
colnames(gut1_aucell) <- sapply(colnames(gut1_aucell), function(x) sub("...", "", x, fixed = TRUE))
gut1_aucell$day <- paste("d", gut1_aucell$day, sep = "")
gut_day_int <- list("d4" = 0, "d7" = 1, "d10" = 2, "d14" = 3, "d21" = 4, "d32" = 5, "d60" = 6, "d90" = 7)

# Filter to just regulons that meet criteria
gut1_regulon_genes <-read.csv("/projects/home/nealpsmith/projects/kupper/kurd_paper/data/pyscenic/gut1/gut1_regulon_genes.csv",
                            row.names = 1)
gut_keep <- intersect(colnames(gut1_regulon_genes), colnames(gut1_aucell))
gut1_aucell <- gut1_aucell[,c(gut_keep, "day")]

gut1_aucell$day_int <- sapply(gut1_aucell$day, function(x) gut_day_int[[x]])

mean_auc_gut <- gut1_aucell %>%
  reshape2::melt(id.vars = c("day", "day_int")) %>%
  group_by(day, day_int, variable) %>%
  summarise(mean_aucell = mean(value)) %>%
  mutate(tissue = "gut")

# Use lienar model to calculate p-values
lm_gut <- lapply(unique(mean_auc_gut$variable), function(reg){
  reg_df <- mean_auc_gut %>%
    dplyr::filter(variable == reg)
  lin_model <- summary(lm(mean_aucell ~ day_int, data = reg_df))
  stat_info <- data.frame(regulon = reg,
                          gut_r_squared = lin_model$r.squared,
                          gut_p_val = as.numeric(lin_model$coefficients[,4][2]),
                          gut_slope = as.numeric(lin_model$coefficients[,1][2]))


  return(stat_info)
}) %>%
  do.call(rbind, .)

lm_gut$gut_adj_pval <- p.adjust(lm_gut$gut_p_val, method = "fdr")

### Now the Skin ###
skin1_aucell <- read.csv('/projects/home/nealpsmith/projects/kupper/pyscenic/res/skin1/skin1.auc_with_timepoint.csv', row.names = 1)
colnames(skin1_aucell) <- sapply(colnames(skin1_aucell), function(x) sub("...", "", x, fixed = TRUE))
skin1_aucell$day <- paste("d", skin1_aucell$day, sep = "")
skin_day_int <- list("d5" = 0, "d10" = 1, "d15" = 2, "d20" = 3, "d25" = 4, "d30" = 5, "d45" = 6, "d60" = 7)

skin1_regulon_genes <- read.csv("/projects/home/nealpsmith/projects/kupper/all_data_analysis/data/integrated/pyscenic/skin1/skin1_regulon_genes.csv",
                            row.names = 1)
skin_keep <- intersect(colnames(skin1_regulon_genes), colnames(skin1_aucell))
skin1_aucell <- skin1_aucell[,c(skin_keep, "day")]

skin1_aucell$day_int <- sapply(skin1_aucell$day, function(x) skin_day_int[[x]])

mean_auc_skin <- skin1_aucell %>%
  reshape2::melt(id.vars = c("day", "day_int")) %>%
  group_by(day, day_int, variable) %>%
  summarise(mean_aucell = mean(value)) %>%
  mutate(tissue = "skin")

# Use lienar model to calculate p-values
lm_skin <- lapply(unique(mean_auc_skin$variable), function(reg){
  reg_df <- mean_auc_skin %>%
    dplyr::filter(variable == reg)
  lin_model <- summary(lm(mean_aucell ~ day_int, data = reg_df))
  stat_info <- data.frame(regulon = reg,
                          skin_r_squared = lin_model$r.squared,
                          skin_p_val = as.numeric(lin_model$coefficients[,4][2]),
                          skin_slope = as.numeric(lin_model$coefficients[,1][2]))
  return(stat_info)
}) %>%
  do.call(rbind, .)

lm_skin$skin_adj_pval <- p.adjust(lm_skin$skin_p_val, method = "fdr")

# Get rid of the ones that are sig in both for this plot
skin_sig <- lm_skin[lm_skin$skin_adj_pval < 0.1 & lm_skin$skin_slope > 0,]
gut_sig <- lm_gut[lm_gut$gut_adj_pval < 0.1 & lm_gut$gut_slope > 0,]
overlap <- intersect(as.character(skin_sig$regulon), as.character(gut_sig$regulon))
skin_sig_unique <- skin_sig$regulon[!skin_sig$regulon %in% overlap]
gut_sig_unique <- gut_sig$regulon[!gut_sig$regulon %in% overlap]

plot_df <- mean_auc_skin %>%
  dplyr::filter(!variable %in% overlap)

plot_df$sig <- ifelse(plot_df$variable %in% skin_sig_unique, "sig", "not_sig")
plot_df$timepoint <- sapply(plot_df$day, function(x) as.numeric(sub("d", "", x)))
plot_df$timepoint <- factor(plot_df$timepoint)
plot_df %<>%
  group_by(variable) %>%
  mutate(dif_from_start = mean_aucell / mean_aucell[day == "d5"]) %>%
  mutate(label = ifelse(day == "d60" & sig == "sig", as.character(variable), NA))

plot_df$sig <- factor(plot_df$sig, levels = c("not_sig", "sig"))
p_skin <- ggplot(plot_df, aes(x = timepoint, y = dif_from_start, group = variable, color = sig)) +
  geom_point(pch = 21, aes(fill = sig)) +
  scale_fill_manual(values = c("grey", "red")) +
  scale_color_manual(values = c("grey", "red")) +
  geom_line() +
  scale_y_log10() +
  annotation_logticks(side = "l", outside = TRUE) +
  coord_cartesian(clip = "off") +
  geom_hline(yintercept = 1, linetype = "dashed") +
  xlab("Day") +
  # ylab("mean AUCell fold-change from baseline") +
  ggtitle("Skin") +
  geom_label_repel(data = plot_df[plot_df$day == "d60",], aes(label = label), color = "black", direction = "x", size = 6) +
  theme_classic(base_size = 20) +
  theme(axis.title.x = element_blank(), axis.title.y = element_blank())

plot_df <- mean_auc_gut %>%
  dplyr::filter(!variable %in% overlap)

plot_df$sig <- ifelse(plot_df$variable %in% gut_sig_unique, "sig", "not_sig")
plot_df$timepoint <- sapply(plot_df$day, function(x) as.numeric(sub("d", "", x)))
plot_df$timepoint <- factor(plot_df$timepoint)
plot_df %<>%
  group_by(variable) %>%
  mutate(dif_from_start = mean_aucell / mean_aucell[day == "d4"])

label_regs <- c("Rb1", "Foxo3", "Myc", "Elf2")
plot_df <- plot_df %>%
  mutate(label = ifelse(day == "d90" & variable %in% label_regs, as.character(variable), NA))

plot_df$sig <- factor(plot_df$sig, levels = c("not_sig", "sig"))
p_gut <- ggplot(plot_df, aes(x = timepoint, y = dif_from_start, group = variable, color = sig)) +
  geom_point(pch = 21, aes(fill = sig)) +
  scale_fill_manual(values = c("grey", "red")) +
  scale_color_manual(values = c("grey", "red")) +
  geom_line() +
  scale_y_log10() +
  annotation_logticks(side = "l", outside = TRUE) +
  coord_cartesian(clip = "off") +
  geom_hline(yintercept = 1, linetype = "dashed") +
  xlab("Day") +
  # ylab("mean AUCell fold-change from baseline") +
  ggtitle("siIEL") +
  geom_label_repel(data = plot_df[plot_df$day == "d90",], aes(label = label), color = "black", size = 6) +
  theme_classic(base_size = 20) +
  theme(axis.title.x = element_blank(), axis.title.y = element_blank())

figure <- ggarrange(plotlist = list(p_skin, p_gut), common.legend = TRUE)
annotate_figure(figure, left = textGrob("mean AUCell fold-change from baseline", rot = 90, vjust = 1, gp = gpar(cex = 1.3)),
                    bottom = textGrob("Day", gp = gpar(cex = 1.3)))

```